[sc-8281] support token flow
smartpay-co/sdk-ruby pull request #17
Opened 2023-01-06 10:14 UTC by hSATAC

2023-01-09 13:51 UTC, othree requested changes

2023-01-09 13:51 UTC, othree commented on spec/smartpay/requests/order_spec.rb
> +                                                  )
Too many spaces here

2023-01-10 03:47 UTC, hSATAC commented on spec/smartpay/requests/order_spec.rb
> +                                                  )
Fixed.

2023-01-10 05:37 UTC, othree approved these changes

2023-01-10 05:59 UTC, merged